{
 "title": "Nginx VTS",
 "description": "nginx_vts_status grafana graph",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Country", "query": "nginx_vts_filter_bytes_total" },
   {
    "name": "Instance",
    "query": "label_values(nginx_vts_server_bytes_total, instance)"
   },
   {
    "name": "Host",
    "query": "label_values(nginx_vts_server_requests_total{instance=~\"$Instance\"}, host)"
   },
   {
    "name": "Upstream",
    "query": "label_values(nginx_vts_upstream_requests_total{instance=~\"$Instance\"}, upstream)"
   },
   {
    "name": "Backend",
    "query": "label_values(nginx_vts_upstream_requests_total{instance=~\"$Instance\", upstream=~\"$Upstream\"}, backend)"
   }
  ]
 },
 "panels": [
  {
   "title": "Server Connections",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_vts_main_connections{instance=~\"$Instance\", status=~\"active|writing|reading|waiting\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "active",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_main_connections{status=\"active\"}[1m]))"
    }
   ]
  },
  {
   "title": "writing",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_main_connections{status=\"writing\"}[1m]))"
    }
   ]
  },
  {
   "title": "read",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_main_connections{status=\"reading\"}[1m]))"
    }
   ]
  },
  {
   "title": "waiting",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_main_connections{status=\"waiting\"}[1m]))"
    }
   ]
  },
  {
   "title": "Server Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_server_requests_total{instance=~\"$Instance\", host=~\"$Host\", code!=\"total\"}[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Upstream Requests",
   "type": "graph",
   "description": "This one is providing aggregated error codes, but it's still possible to graph these per upstream.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_upstream_requests_total{instance=~\"$Instance\", upstream=~\"^$Upstream$\", backend=~\"^$Backend$\", code!=\"total\"}[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Request delta/sec (BACKEND)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Rate" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_upstream_requests_total{backend=~\"$Backend\", instance=~\"$Instance\", code!=\"total\"} [1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Request delta/sec (FILTER)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Rate" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_filter_requests_total{filter=~\"country::$Host\", filter_name=~\"$Country\", instance=~\"$Instance\", direction!=\"total\"} [1m])) by (direction)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Response times (FILTER)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_filter_request_seconds{filter=~\"country::$Host\", filter_name=~\"$Country\", instance=~\"$Instance\"} [1m])) by (filter_name) * 1000",
     "legendFormat": "{{filter_name}}"
    }
   ]
  },
  {
   "title": "bandwith delta/sec (FILTER)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes", "label": "Rate" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_filter_bytes_total{filter=~\"country::$Host\", filter_name=~\"$Country\", instance=~\"$Instance\"} [1m])) by (direction)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Server Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_server_bytes_total{instance=~\"$Instance\", host=~\"$Host\"}[5m])) by (direction)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Upstream Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_upstream_bytes_total{instance=~\"$Instance\", upstream=~\"^$Upstream$\", backend=~\"^$Backend$\"}[5m])) by (direction)",
     "legendFormat": "{{ direction }}"
    }
   ]
  },
  {
   "title": "Upstream Backend Response",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nginx_vts_upstream_response_seconds{instance=~\"$Instance\", upstream=~\"^$Upstream$\", backend=~\"^$Backend$\"}) by (backend)",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Server Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_vts_server_cache_total{instance=~\"$Instance\", host=~\"$Host\"}[5m])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  }
 ]
}